# Form implementation generated from reading ui file 'C:\Users\пк\PycharmProjects\pythonProject\YL_current\YL\GUI\Game.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Game(object):
    def setupUi(self, Game):
        Game.setObjectName("Game")
        Game.resize(786, 622)
        Game.setStyleSheet("background-color: rgb(54, 54, 54)")
        self.centralwidget = QtWidgets.QWidget(parent=Game)
        self.centralwidget.setObjectName("centralwidget")
        self.input_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_line.setGeometry(QtCore.QRect(210, 270, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.input_line.setFont(font)
        self.input_line.setStyleSheet("background-color: rgb(91, 91, 91);\n"
"color: rgb(239, 239, 239)")
        self.input_line.setText("")
        self.input_line.setObjectName("input_line")
        self.point_counter = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.point_counter.setGeometry(QtCore.QRect(650, 40, 101, 51))
        self.point_counter.setObjectName("point_counter")
        self.stop_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(330, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("color: rgb(239, 239, 239);\n"
"background-color: rgb(91, 91, 91);")
        self.stop_btn.setObjectName("stop_btn")
        self.statistics = QtWidgets.QPushButton(parent=self.centralwidget)
        self.statistics.setGeometry(QtCore.QRect(590, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statistics.setFont(font)
        self.statistics.setStyleSheet("background-color: rgb(91, 91, 91);\n"
"color: rgb(239, 239, 239);")
        self.statistics.setObjectName("statistics")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 10, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet(";\n"
"background-color: rgb(91, 91, 91);color: rgb(239, 239, 239)")
        self.back.setObjectName("back")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(239, 239, 239)")
        self.label_2.setObjectName("label_2")
        self.id_label = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(290, 30, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_label.setFont(font)
        self.id_label.setStyleSheet("color: rgb(239, 239, 239);")
        self.id_label.setText("")
        self.id_label.setObjectName("id_label")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(150, 180, 471, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(239, 239, 239);\n"
"border-color: rgb(239, 239, 239);")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        Game.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Game)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        Game.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Game)
        self.statusbar.setObjectName("statusbar")
        Game.setStatusBar(self.statusbar)

        self.retranslateUi(Game)
        QtCore.QMetaObject.connectSlotsByName(Game)

    def retranslateUi(self, Game):
        _translate = QtCore.QCoreApplication.translate
        Game.setWindowTitle(_translate("Game", "Game"))
        self.stop_btn.setText(_translate("Game", "Стоп"))
        self.statistics.setText(_translate("Game", "Статистика"))
        self.back.setToolTip(_translate("Game", "Вернуться в меню"))
        self.back.setText(_translate("Game", "<"))
        self.label_2.setText(_translate("Game", "Ваш ID ="))
        self.label.setText(_translate("Game", "Начать!"))
